#!/bin/sh

rm ${DESTDIR}/lib/zumastor >/dev/null 2>&1 # in case of symlink
rm ${DESTDIR}/var/lib/zumastor >/dev/null 2>&1 # in case of symlink
rm ${DESTDIR}/var/run/zumastor >/dev/null 2>&1 # in case of symlink
rm ${DESTDIR}/etc/zumastor >/dev/null 2>&1 # in case of symlink

echo ${DESTDIR}
mkdir -p ${DESTDIR}
echo ${DESTDIR}/t.tar
tar -cv --exclude=.svn --exclude=Makefile --exclude=TODO --exclude=notes.packaging --exclude=debian --exclude=scripts -f ${DESTDIR}/t.tar *

cd ${DESTDIR}
tar xvf t.tar
cd -

rm ${DESTDIR}/t.tar

chmod 755 ${DESTDIR}/etc/cron.{hourly,daily,weekly}/zumastor ${DESTDIR}/etc/init.d/zumastor
