#!/bin/bash

. /lib/zumastor/common

[[ $# -eq 2 ]] || { echo "usage: $0 <volume> <target>"; exit 1; }
declare vol=$1
declare host=$2
declare sendfile=$VOLUMES/$vol/targets/$host/send
declare sock=$SERVERS/$vol
declare size=$(ddsnap status $sock --size) || exit 1

while true; do
	replicating=yes
	read snap chunks_sent <$sendfile 2>/dev/null || replicating=
	clear
	if [[ -z $replicating ]]; then
		echo "Not replicating"
		sleep 5
	else
		[[ -z $chunks_sent ]] && chunks_sent=0
		per=$(($chunks_sent*100/$size))
		echo Sending snapshot $snap: $chunks_sent/$size "($per%)"
		sleep 1
	fi
done
