.TH ddsnap-sb 8 "Apr 29, 2008" "Linux"
.SH NAME
ddsnap-sb \- ddsnap helper program for upgrading ddsnap ondisk superblock structure.

\fB
.SH SYNOPSIS
.B ddsnap-sb
.br
.SH DESCRIPTION
\fBddsnap-sb\fP is used to upgrade the ondisk superblock of an existing ddsnap volume 
to the latest version.

.SH BUGS
Please report bugs at \fBhttp://code.google.com/p/zumastor\fP or mail them to \fBzumastor@googlegroups.com\fP.

.SH VERSION
This man page is current for version 0.8 of \fBddsnap-sb\fP.

.SH AUTHORS
.TP
zumastor-team

.SH THANKS
.TP
Thanks to Google, Red Hat and Sistina Software for supporting this work.  Special thanks to: Mike Todd, Joseph Dries and Matthew O'Keefe.
.TP
The home page of \fBddsnap-sb\fP is \fBhttp://zumastor.org\fP.  This site may cover questions unanswered by this manual page.  Mailing lists for support and development are available at zumastor@googlegroups.com
