.TH nblock_write 8 "Apr 24, 2008" "Linux"
.SH NAME
nblock_write \- Nonblocking write program for unix sockets

\fB
.SH SYNOPSIS
.B nblock_write
.br
.SH DESCRIPTION
\fBnblock_write\fP is used to perform a non-blocking write to a unix socket


.SH BUGS
Please report bugs at \fBhttp://code.google.com/p/zumastor\fP or mail them to \fBzumastor@googlegroups.com\fP.

.SH VERSION
This man page is current for version 0.8 of \fBnblock_write\fP.

.SH AUTHORS
.TP
zumastor-team

.SH THANKS
.TP
Thanks to Google, Red Hat and Sistina Software for supporting this work.  Special thanks to: Mike Todd, Joseph Dries and Matthew O'Keefe.
.TP
The home page of \fBnblock_write\fP is \fBhttp://zumastor.org\fP.  This site may cover questions unanswered by this manual page.  Mailing lists for support and development are available at zumastor@googlegroups.com
