#!/bin/bash
# Zumastor Linux Storage Server
# Copyright (c) 2006 Google Inc.
# Author: Daniel Phillips <phillips@google.com>
# Licensed under the GNU GPL version 2

. /lib/lsb/init-functions || { echo "$0: unable to load LSB init functions"; exit 1; }
. /lib/zumastor/common || { echo "$0: unable to load common zumastor functions"; exit 1; }
. /lib/zumastor/ddfake

function start_zumastor {
	echo Starting zumastor
	local vol
	local id
	local host

	# setup directory structure
	if ! [ -d $RUNPATH ]; then
		mkdir -p $AGENTS || return 1
		mkdir -p $SERVERS || return 1
		mkdir -p $CRONS || return 1
		mkdir -p $MOUNTS || return 1
	fi

	touch $RUNFILE

	for vol in $(ls $VOLUMES); do
		start_volume $vol || return 1

		create_device $vol -1 || return 1
		local -r list=$(get_managed_snapshots $vol) || return 1
		for id in $list; do
			create_device $vol $id || return 1
		done

		if [ -x $VOLUMES/$vol/master ]; then
			zumastor start master $vol || return 1
		else
			# start the nag daemon
			if [ -x $VOLUMES/$vol/source ]; then
				zumastor start source $vol
			else
				echo "info: orphan volume '$vol' is neither master nor slave"
			fi
		fi

		for host in $(ls $VOLUMES/$vol/targets); do
			zumastor start target $vol $host
		done

	done
}

function stop_zumastor {
	echo Stopping zumastor
	local vol
	local id
	local host

	for vol in $(ls $VOLUMES); do
		for host in $(ls $VOLUMES/$vol/targets); do
			zumastor stop target $vol $host
		done
		if [ -x $VOLUMES/$vol/master ]; then
			zumastor stop master $vol
		fi

		for id in $(get_managed_snapshots $vol); do
			umount_device $vol $id 2>/dev/null
			remove_device $vol $id
		done
		umount_device $vol -1 2>/dev/null
		remove_device $vol -1

		stop_volume $vol
	done
}

[ -d $VOLUMES ] || { echo "$0: cannot find zumastor database in '$VOLUMES'"; exit 1; }

case $1 in
start)
	if [ -e $RUNFILE ]; then
		echo "$RUNFILE exists, is zumastor already running?"
		exit 1
	fi
	start_zumastor
	;;

stop)
	stop_zumastor
	[ -e $RUNFILE ] && rm $RUNFILE

	;;

restart|force-reload)
	stop_zumastor
	start_zumastor
	;;
status)
	if [ -e $RUNFILE ]; then
		echo zumastor is running
		echo "use 'zumastor status' for more info..."
	else
		echo zumastor is NOT running
	fi
	exit 0
	;;
*)
	echo "Usage: $0 {start|stop|restart|force-reload}"
	exit 2
	;;
esac
