#!/bin/bash

source_uml_ip=192.168.100.5
source_uml_host=uml_5
source_uml_fs=uml_fs5

target_uml_ip=192.168.100.6
target_uml_host=uml_6
target_uml_fs=uml_fs6

source_ubdb_dev=$PWD/source_ubdb
source_ubdc_dev=$PWD/source_ubdc
target_ubdb_dev=$PWD/target_ubdb
target_ubdc_dev=$PWD/target_ubdc

vol="test"
hourly_snapnum=3600
target_port=11235
interval=1
VOLUMES=/var/lib/zumastor/volumes
SSH_OPTS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
