#!/bin/bash

# ZUMA_REPOSITORY is the path of the zumastor code
ZUMA_REPOSITORY="${PWD}/../.."

KERNEL_VERSION=`awk '/^2\.6\.[0-9]+(\.[0-9]+)?$/ { print $1; }' $ZUMA_REPOSITORY/KernelVersion`
if [ "x$KERNEL_VERSION" = "x" ] ; then
  echo "Suspect KernelVersion file"
  exit 1
fi
    
LOG=`mktemp`
host_tap_ip=192.168.100.111
